### ISSUE TITLE
Failing to copy AXIS jars in org.eclipse.jst.ws.internal.axis.consumption.ui.task.CopyAxisJarCommand

### ISSUE THREAD

**Issue by pnickoll** [eclipse-webservices/webservices#3]
Hi,

Sometime in 2023 (it worked in 2023-03 but not in 2023-12 - not narrowed it down more) the CopyAxisJarCommand started to throw exceptions like this:

```
java.io.FileNotFoundException: /lib/commons-discovery-0.2.jar
	at org.eclipse.osgi.storage.url.bundleentry.Handler.findBundleEntry(Handler.java:55)
	at org.eclipse.osgi.storage.url.BundleResourceHandler.openConnection(BundleResourceHandler.java:182)
	at java.base/java.net.URL.openConnection(URL.java:1094)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at org.eclipse.jst.ws.internal.axis.consumption.ui.task.CopyAxisJarCommand.copyIFile(CopyAxisJarCommand.java:210)
	at org.eclipse.jst.ws.internal.axis.consumption.ui.task.CopyAxisJarCommand.copyAxisJarsToProject(CopyAxisJarCommand.java:163)
	at org.eclipse.jst.ws.internal.axis.consumption.ui.task.CopyAxisJarCommand.execute(CopyAxisJarCommand.java:124)
	at org.eclipse.jst.ws.internal.axis.creation.ui.command.BUCodeGenOperation$BottomUpWSModifyOperation.execute(BUCodeGenOperation.java:119)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:110)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:131)
	at org.eclipse.jst.ws.internal.axis.creation.ui.command.BUCodeGenOperation.execute(BUCodeGenOperation.java:90)
	at org.eclipse.wst.command.internal.env.core.fragment.CommandFragmentEngine.runCommand(CommandFragmentEngine.java:421)
	at org.eclipse.wst.command.internal.env.core.fragment.CommandFragmentEngine.visitTop(CommandFragmentEngine.java:361)
	at org.eclipse.wst.command.internal.env.core.fragment.CommandFragmentEngine.moveForwardToNextStop(CommandFragmentEngine.java:256)
	at org.eclipse.wst.command.internal.env.ui.widgets.SimpleCommandEngineManager$6.run(SimpleCommandEngineManager.java:296)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:434)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:470)
	at org.eclipse.wst.command.internal.env.ui.widgets.SimpleCommandEngineManager.runForwardToNextStop(SimpleCommandEngineManager.java:266)

```

I believe this may be a result of the two Eclipse plugins no longer shipping the jars that CopyAxisJarCommand is looking for, namely

1. org.apache.axis jar moved from 1.4.0 and no longer contains the lib dir with axis.jar in
2. org.apache.commons.discovery moved from 0.2.0 to 0.5/0 and no longer ships commons-discovery-0.2.jar

I can see in CopyAxisJarCommand the line

`copyIFile(COMMON_DISCOVERY_PLUGIN_ID, null, null, "lib/" + COMMON_DISCOVERY_JAR, webModulePath, "WEB-INF/lib/" + COMMON_DISCOVERY_JAR, status, env, monitor);`

And I think that is referring to the now removed jars files. I am not sure if this needs updating or the files it is referencing needs to be re-introduced.

**Comment by pnickoll** [comment]
@nitind Is this something you might know about?

**Comment by nitind** [comment]
> @nitind Is this something you might know about?

Not in the least, but your analysis so far looks right to me.
